# Generated by Django 4.1 on 2022-08-29 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamiliares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='año_de_nacimiento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
