# Generated by Django 4.1 on 2022-08-29 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamiliares', '0002_familiar_año_de_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='año_de_nacimiento',
            new_name='fecha',
        ),
    ]
